FROM node:18

WORKDIR /app

COPY package*.json ./
# Tambahkan flag ini untuk menghindari konflik dependency
RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
